"""
QR Code Freshers Welcome + Scratch Card Project
-------------------------------------------------
Run this Flask app, generate a QR code (generate_qr.py) that points to this
server's URL, and when a fresher scans it they land on a Welcome page.
Clicking "Continue" takes them to a Scratch Card page. Scratching the card
calls a Python API (/api/random-message) that returns a random funny
welcome message with an emoji, which pops up once fully scratched.

Run:
    pip install -r requirements.txt
    python app.py

Then open the printed local URL, or scan the QR code generated by
generate_qr.py (make sure your phone & laptop are on the same WiFi).
"""

from flask import Flask, render_template, jsonify
import random

app = Flask(__name__)

# 20 funny, friendly (non-hurtful) fresher welcome messages with emojis
FUNNY_MESSAGES = [
     "🌱 கனவு காணுங்கள்... அந்தக் கனவுக்காக உழைக்கத் தொடங்குங்கள்.",
     "🚀 இன்றைய முயற்சி நாளைய வெற்றியின் அடித்தளம்.",
     "💡 கற்றலை நேசியுங்கள்... வெற்றி உங்களைத் தேடி வரும்.",
     "📚 ஒவ்வொரு நாளும் புதிதாக ஒன்றைக் கற்றுக்கொள்ளுங்கள்.",
     "🌟 உங்கள் திறமையை உலகிற்கு நிரூபியுங்கள்.",
     "🎯 சிறிய தொடக்கம் கூட பெரிய வெற்றியை உருவாக்கும்.",
     "🤝 நல்ல நட்புகள் நல்ல எதிர்காலத்தை உருவாக்கும்.",
     "💻 தொழில்நுட்பத்தை பயன்படுத்த மட்டும் அல்ல... ருவாக்கவும் கற்றுக்கொள்ளுங்கள்.",
     "🌍 அறிவே உங்கள் மிகப்பெரிய சொத்து.",
     "🔥 தோல்வி முடிவு அல்ல... அடுத்த முயற்சிக்கான தொடக்கம்.",
     "🌱 நம்பிக்கை இருக்கும் இடத்தில் வெற்றி தூரமில்லை.",
     "🎓 பட்டம் ஒரு சான்றிதழ்... திறமைதான் உண்மையான அடையாளம்.",
     "💙 கேள்வி கேட்கத் தயங்காதீர்கள்... அதுவே அறிவின் முதல் படி.",
     "📖 ஒவ்வொரு அனுபவமும் ஒரு புதிய பாடம்.",
     "✨ உங்கள் எதிர்காலத்தை உருவாக்கும் சக்தி உங்களிடமே உள்ளது.",
     "🚀 உழைப்பு ஒருபோதும் வீணாகாது.",
     "🌟 மாற்றத்தை எதிர்பார்க்காதீர்கள்... மாற்றத்தை உருவாக்குங்கள்.",
     "💡 சிந்தனை உயர்ந்தால் சாதனையும் உயர்ந்தே இருக்கும்.",
      "🤝 ஒன்றாகக் கற்றால் உயரமாக வளரலாம்.",
     "🎯 இன்று நீங்கள் எடுக்கும் ஒரு நல்ல முடிவு, நாளைய வெற்றியை தீர்மானிக்கும்."
]


@app.route("/")
def welcome():
    """Welcome page shown right after the QR code is scanned."""
    return render_template(
        "welcome.html",
        title="Step Into The World Of IT !!",
        subtitle="Code your dreams, built your future.",
    )


@app.route("/scratch")
def scratch():
    """Scratch card page."""
    return render_template("scratch.html")


@app.route("/api/random-message")
def random_message():
    """API used by the scratch card JS to fetch a random funny message."""
    message = random.choice(FUNNY_MESSAGES)
    return jsonify({"message": message})


if __name__ == "__main__":
    # host=0.0.0.0 so phones on the same WiFi (via QR code) can reach it too
    app.run(host="0.0.0.0", port=5000, debug=True)
